const constants = {
  SET_SORT_PARAMETER : 'SET_SORT_PARAMETER',
  SET_SORT_ORDER : 'SET_SORT_ORDER',
  GET_SORT_CRITERIA: 'GET_SORT_CRITERIA',

  GET_ALL_POSTS: 'GET_ALL_POSTS',
  GET_CATEGORY_POSTS: 'GET_CATEGORY_POSTS',
  GET_SINGLE_POST: 'GET_SINGLE_POST',
  CREATE_POST: 'CREATE_POST',
  ADD_POST: 'ADD_POST',
  VOTE_POST: 'VOTE_POST',
  UPDATE_POST: 'UPDATE_POST',
  DELETE_POST: 'DELETE_POST',

  GET_POST_COMMENTS: 'GET_POST_COMMENTS',
  GET_SINGLE_COMMENT : 'GET_SINGLE_COMMENT',
  ADD_COMMENT : 'ADD_COMMENT',
  UPDATE_COMMENT : 'UPDATE_COMMENT',
  VOTE_COMMENT : 'VOTE_COMMENT',
  DELETE_COMMENT : 'DELETE_COMMENT',

  GET_ALL_CATEGORIES : 'GET_ALL_CATEGORIES'
}

export default constants